/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ipc365_app_showmo_jni_JniClient */

#ifndef _Included_ipc365_app_showmo_jni_JniClient
#define _Included_ipc365_app_showmo_jni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Init
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetLastError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetVerifyCode
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetVerifyCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_ENT_GetAppVersion
 * Signature: (ILipc365/app/showmo/jni/JniDataDef/QueryAppVersionRet;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1ENT_1GetAppVersion
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_AddTerminal
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/TerminalDeviceAddReq;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1AddTerminal
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_ResetPassword
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/ResetPasswordReq;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1ResetPassword
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_ResetPasswordEx
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/ResetPasswordByVerifyReq;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1ResetPasswordEx
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetDeviceid
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetDeviceid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_BindState
 * Signature: (Ljava/lang/String;)Lipc365/app/showmo/jni/JniDataDef/BindStateInfo;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1BindState
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_CheckVerifyCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1CheckVerifyCode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_AddDevice
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/ClientDeviceAddReq;)Lipc365/app/showmo/jni/JniDataDef/ClientDeviceAddRet;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1AddDevice
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_AddDeviceEx
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/ClientDeviceAddReq;)Lipc365/app/showmo/jni/JniDataDef/ClientDeviceAddRet;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1AddDeviceEx
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_DeleteDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1DeleteDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_VerityAccount
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1VerityAccount
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_ApplyTestAccount
 * Signature: (I)Lipc365/app/showmo/jni/JniDataDef/SDK_APPLY_ACCOUNTINFO;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1ApplyTestAccount
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_DeleteApplyAccount
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/SDK_APPLY_ACCOUNTINFO;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1DeleteApplyAccount
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SignUp
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/ClientRegister2Login;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SignUp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Mgr_SignIn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Mgr_1SignIn
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Mgr_DisConnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Mgr_1DisConnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Login
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/ClienteLoginReq;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Login
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Logout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Logout
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_OnLineState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1OnLineState
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetLocalVerity
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetLocalVerity
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_StartRealPlay
 * Signature: (ILipc365/app/showmo/jni/JniDataDef/OnRealdataCallBackListener;J)I
 */
JNIEXPORT jint JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1StartRealPlay
  (JNIEnv *, jclass, jint, jobject, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SetStreamType
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SetStreamType
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Panoinfo
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/PanoInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Panoinfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SetMsgDataCallBack
 * Signature: (Lipc365/app/showmo/jni/OnMsgDataCallBackWraper;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SetMsgDataCallBack
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SetAlarmState
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SetAlarmState
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetAlarmState
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetAlarmState
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetAlarmPic
 * Signature: (Ljava/lang/String;IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetAlarmPic
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_ReleaseBuf
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1ReleaseBuf
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_StopRealPlay
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1StopRealPlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Audio
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Audio
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetDeviceList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetDeviceList
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Log
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Log
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Upgrade
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Upgrade
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_BrightCtrl
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1BrightCtrl
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SearchRemoteFile
 * Signature: (ILipc365/app/showmo/jni/JniDataDef/SDK_SEARCH;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SearchRemoteFile
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_PlayBack
 * Signature: (ILipc365/app/showmo/jni/JniDataDef/SDK_REMOTE_FILE;Lipc365/app/showmo/jni/JniDataDef/OnRealdataCallBackListener;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1PlayBack
  (JNIEnv *, jclass, jint, jobject, jobject, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetPlayBackPos
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetPlayBackPos
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_PlayBackControl
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1PlayBackControl
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_StopPlayBack
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1StopPlayBack
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Record
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Record
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_StopRecord
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1StopRecord
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetDevConfig
 * Signature: (JLjava/lang/String;JLjava/lang/String;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetDevConfig
  (JNIEnv *, jclass, jlong, jstring, jlong, jstring, jlong, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SetDevConfig
 * Signature: (JLjava/lang/String;JLjava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SetDevConfig
  (JNIEnv *, jclass, jlong, jstring, jlong, jstring, jlong, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetFrameSize
 * Signature: ([BI)Lipc365/app/showmo/jni/JniDataDef/FrameSize;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetFrameSize
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_GetTalkState
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1GetTalkState
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_TalkCtrl
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1TalkCtrl
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SendTalkData
 * Signature: (I[BJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SendTalkData
  (JNIEnv *, jclass, jint, jbyteArray, jlong, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_ModifyDevName
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1ModifyDevName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_Brightness
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1Brightness
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_NET_SetDebugDatacallback
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/OnDebugDataCallbackListener;)I
 */
JNIEXPORT jint JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1NET_1SetDebugDatacallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevLogin
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevLogin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevLogout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevLogout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevSetTimezone
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevSetTimezone
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevSetOSD
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevSetOSD
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevSetWifi
 * Signature: (JLipc365/app/showmo/jni/JniDataDef/PW_PHONE_BL_WIFI_CONFIG;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevSetWifi
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_isDevConnectedInApModel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1isDevConnectedInApModel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_GetConnectedRouterStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1GetConnectedRouterStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevSetDHCP
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevSetDHCP
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevAlive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevAlive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_DevAPSwap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1DevAPSwap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_BeginCycleBroadcastToDev
 * Signature: (Lipc365/app/showmo/jni/JniDataDef/Broadcast_wifi_info;)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1BeginCycleBroadcastToDev
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_StopCycleBroadcastToDev
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1StopCycleBroadcastToDev
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_SetPauseCycleBroadcastToDev
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1SetPauseCycleBroadcastToDev
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    PW_PRI_SearchDevInLan
 * Signature: (I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_PW_1PRI_1SearchDevInLan
  (JNIEnv *, jclass, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    pw_jni_call_test
 * Signature: ()Lipc365/app/showmo/jni/JniDataDef/User_2_mgr_disconn_device;
 */
JNIEXPORT jobject JNICALL Java_ipc365_app_showmo_jni_JniClient_pw_1jni_1call_1test
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1init
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_setPpi
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1setPpi
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_setPpiXy
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1setPpiXy
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_PatternCtrlFingerDown
 * Signature: (I[Lcom/puwell/opengles/Flinger;II)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1PatternCtrlFingerDown__I_3Lcom_puwell_opengles_Flinger_2II
  (JNIEnv *, jclass, jint, jobjectArray, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_PatternCtrlFingerDown
 * Signature: (I[I[I[I[III)V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1PatternCtrlFingerDown__I_3I_3I_3I_3III
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_GetPatternWithTime
 * Signature: (ILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1GetPatternWithTime
  (JNIEnv *, jclass, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1Stop
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1Start
  (JNIEnv *, jclass);

/*
 * Class:     ipc365_app_showmo_jni_JniClient
 * Method:    native_mpgl_reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ipc365_app_showmo_jni_JniClient_native_1mpgl_1reset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
