package com.showmo.network;

public interface NetWorkErrorCode {

	int RESPONSE_OK = 0;
	int RESPONSE_FAILED = 1;
	int CSP_ERROR_SUCCESS = 2;

	//user  			[100,200)
	int	CSP_ERROR_NAME_REPEATED = 100;
	int	CSP_ERROR_GET_USER_DETAIL = 101;
	int	CSP_ERROR_USER_NAME_NOTEXIST = 102;
	int	CSP_ERROR_UESR_NAME_NULL = 103 ;
	int	CSP_ERROR_USER_KEY_WRONG = 104 ;
	int	CSP_ERROR_USER_GET_DEVICE_LIST = 105 ;
	int	CSP_ERROR_USER_TYPE_WRONG = 106 ;	 //”√ªß¿‡–Õ¥ÌŒÛ	«Î«Û≤‚ ‘’À∫≈,≤‚ ‘’À∫≈ªÿ ’
	int	CSP_ERROR_USER_NO_DEMO_USER = 107 ; //‘›Œﬁ≤‚ ‘’À∫≈	«Î«Û≤‚ ‘’À∫≈

	//custom  			[200,300)
	int	CSP_ERROR_GET_CUSTOMER_DETAIL = 200;
	int	CSP_ERROR_GET_CUSTOMER_GROUPS = 201;
	int		CSP_ERROR_GET_CUSTOMER_LIST= 202;
	int	CSP_ERROR_CUSTOM_GET_DEVICE_LIST = 203;
	int	CSP_ERROR_CUSTOM_GET_USER_LIST = 204;

	//register,login  	[300,400)
	int	CSP_ERROR_REGISTER_MSG_NULL = 300;
	int	CSP_ERROR_RESETKEY_MSG_NULL = 301;
	int	CSP_ERROR_LOGIN_FAILED = 303;

	//device     		[400,500)
	int		CSP_ERROR_GET_DEVICE_ID = 400 ;
	int		CSP_ERROR_ADD_DEVICE = 401 ;
	int		CSP_ERROR_GET_DEVICE = 403 ;
	int		CSP_ERROR_DEL_DEVICE = 404 ;
	int		CSP_ERROR_GET_DEVICE_DETAIL = 405 ;
	int		CSP_ERROR_DEVICE_GET_CAMERA_LIST = 406 ;
	int		CSP_ERROR_DEVICE_GET_CUSTOM = 407 ;
	int		CSP_ERROR_DEVICE_STATUS_NOTEXIST = 408 ;
	int		CSP_ERROR_DEVICE_STATUS_ADDED = 409 ;
	int		CSP_ERROR_DEVICE_STATUS_ABANDONED = 410 ;
	int 		CSP_ERROR_DEVICE_STATUS_WRONG = 411 ;

	//camera   			[500,600)
	int		CSP_ERROR_GET_CAMERA_DETAIL  = 500 ;
	int		CSP_ERROR_CAMERA_GET_CUSTOM = 501 ;
	//terminaldevice   	[600,700)
	int		CSP_ERROR_TERMINAL_DEVICE_NULL  = 600;
	int		CSP_ERROR_TERMINAL_DEVICE_EXISTED = 601;
	int		CSP_ERROR_TERMINAL_DEVICE_NOTEXIST = 603;
	int		CSP_ERROR_GET_TERMINAL_DEVICE = 604;

	//terminalexception [700,800)
	int		CSP_ERROR_ADD_TERMINAL_EXCEPTION = 700;

	//Verifycode  		[800,900)
	int 	CSP_ERROR_SEND_VERIFYCODE = 800 ;
	int 	CSP_ERROR_VERIFYCODE_NULL = 801 ;
	int 	CSP_ERROR_VERIFYCODE_WRONG = 802 ;	

	//app  				[900,1000)
	int	CSP_ERROR_GET_APPVERSION = 900;

	//MOD 2014.12.8

	//old				[1000,1100)
	int	CSP_ERROR_JOIN_DEPARTMENT  = 1000;
	int	CSP_ERROR_GET_DEPARTMENTS  = 1001;
	int	CSP_ERROR_DEL_EMPLOYEE   = 1002;
	int	CSP_ERROR_GET_AUTH_CAMERAS  = 1003;
	int	CSP_ERROR_GET_RIGHTS  = 1004;
	int	CSP_ERROR_UPDATE_USER  = 1005;
	int	CSP_ERROR_GET_ADMIN_FAILED  = 1006;
	int	CSP_ERROR_ADMIN_NOT_ONLINE  = 1007;
	int	CSP_ERROR_QUERY_FROM_STATUS_FAILED  = 1008;

	//◊¥Ã¨∞¸¥˙¬Î		[1100,1200)
	int	CSP_STATE_START_LOOK_CAMERA_OK = 1100;
	int	CSP_STATE_GET_PARTNERS_FAILED = 1101;
	int	CSP_STATE_ASK_BAKFRAME_FAILED = 1102;
	int	CSP_STATE_ASK_INIT_BUF_FAILED = 1103;
	int	CSP_STATE_MGR_SIGN_IN_OK = 1104;
	int	CSP_STATE_MGR_SIGN_IN_FAILED = 1105;
	int	CSP_STATE_VD_SIGN_IN_OK = 1106;
	int	CSP_STATE_VD_SIGN_IN_FAILED = 1107;
	int	CSP_STATE_MGR_CLIENT_ONLINE_OK = 1108;
	int	CSP_STATE_MGR_CLIENT_ONLINE_FAILED = 1109;

	//other 			[1200,1300)
	int	CSP_ERROR_INVALID_SESSION_ID = 1200;
	int	CSP_ERROR_DOMAIN = 1250;
	int	CSP_ERROR_NO_INIT = 1500;
	int	CSP_ERROR_MGR_NOLINK = 1501;
	int	CSP_ERROR_VIDEO_NOLINK = 1502;
	int	CSP_ERROR_IPC_NOLINK = 1503;
	int CSP_ERROR_IPC_NOIP = 1505;
	int CSP_ERROR_IPC_CONN = 1506;
	int CSP_ERROR_LOGIN_CONN = 1507;

	int	CSP_ERROR_SOCKET_CREATE = 2000;
	int	CSP_ERROR_SOCKET_CONNECT = 2001;
	int	CSP_ERROR_SOCKET_BIND = 2002;
	int	CSP_ERROR_SOCKET_SEND = 2003;
	int	CSP_ERROR_MEMORY_ERROR = 2004;
	int	CSP_ERROR_DATA_NOMATCH = 3000; 
	int	CSP_ERROR_ILLEGAL_PARAM = 4000;
	int	CSP_ERROR_TIMEOUT = 5000;
	int	CSP_ERROR_LOGIN_REPEAT = 5001;
	int CSP_ERROR_LOGIN_IN_OTHER_INTERMINAL=1201;
}